boilerplate:
  oauth2:
    jwt-issuer: ${ISSUER_URL:http://localhost:8081/realms/custom_realm}
  db:
    host: ${BOILERPLATE_DATABASE_HOST:localhost}
    port: ${BOILERPLATE_DATABASE_POST:5432}
    name: ${BOILERPLATE_DATABASE_NAME:local}
    user: ${BOILERPLATE_DATABASE_USERNAME:localhost}
    pass: ${BOILERPLATE_DATABASE_PASSWORD:password}

spring:
  application:
    name: boilerplate.api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${boilerplate.db.host}:${boilerplate.db.port}/${boilerplate.db.name}
    username: ${boilerplate.db.user}
    password: ${boilerplate.db.pass}
  flyway:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${boilerplate.oauth2.jwt-issuer}
  main:
    web-application-type: servlet
  threads:
    virtual:
      enabled: true
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      enabled: true
      mode: full
    env:
      enabled: true
info:
  application:
    name: My API Boilerplate
debug: false
server:
  servlet:
    context-path: ''